desarrolloEureka/onTap

- app/[lang]/views/home/Home.tsx
> feat: test

- app/[lang]/components/menu/Menu.tsx
- app/[lang]/hooks/user/UserHook.tsx
- app/[lang]/hooks/validatorSession/ValidatorSession.tsx
- app/[lang]/types/menu.ts
- app/[lang]/views/home/hooks/HomeHook.tsx
- app/[lang]/views/login/hooks/LoginHookMain.tsx
- app/[lang]/views/recoverpassword/page.tsx
> feat: new navbar

- app/[lang]/components/menu/Menu.tsx
- app/[lang]/views/home/page.tsx
- app/[lang]/views/home/profile/Profile.tsx
- app/[lang]/views/profile/page.tsx
> feat: profile merge into navbar

- app/[lang]/types/dictionary.ts
- app/[lang]/views/home/page.tsx
- app/[lang]/views/profile/components/FooterProfile.tsx
- app/[lang]/views/profile/components/FormAddDataUser.tsx
- app/[lang]/views/profile/components/ModalProfile.tsx
- app/[lang]/views/profile/page.tsx
- dic/es.json
> bugfix: text correction and addition of template icons

- app/[lang]/components/login/Login.tsx
- app/[lang]/components/menu/Menu.tsx
- app/[lang]/views/recoverPassword/components/RecoveryCode.tsx
- app/[lang]/views/recoverPassword/components/RecoveryPassword.tsx
> Cristian g/bug fix

- app/[lang]/types/dictionary.ts
- app/[lang]/views/home/components/profile/FormAddDataUser.tsx
- app/[lang]/views/home/components/profile/ItemFormBasicInfo.tsx
- app/[lang]/views/home/components/profile/ItemFormEducation.tsx
- app/[lang]/views/home/components/profile/ItemFormProfessional.tsx
- app/[lang]/views/home/components/profile/hooks/ProfileHook.tsx
- app/[lang]/views/recoverPassword/components/RecoveryPassword.tsx
> bugfix: correction onchange inputs

- app/[lang]/views/home/components/form/FormDataUser.tsx
- app/[lang]/views/home/components/header/Header.tsx
- app/[lang]/views/home/components/homeContent/HomeContent.tsx
- app/[lang]/views/home/components/profile/FormAddDataUser.tsx
- app/[lang]/views/home/components/profile/ModalProfile.tsx
- app/[lang]/views/home/components/profile/Profile.tsx
> feat: responsive application

- app/[lang]/components/customSwitch/CustomSwitch.tsx
- app/[lang]/components/menu/Menu.tsx
- app/[lang]/types/dictionary.ts
- app/[lang]/views/home/components/form/FormDataUser.tsx
- app/[lang]/views/home/components/homeContent/HomeContent.tsx
- app/[lang]/views/home/components/profile/ItemFormBasicInfo.tsx
- app/[lang]/views/home/components/profile/ItemFormEducation.tsx
- app/[lang]/views/home/components/profile/ItemFormProfessional.tsx
- app/[lang]/views/home/components/profile/ModalProfile.tsx
- app/[lang]/views/home/components/profile/hooks/ProfileHook.tsx
- dic/es.json
> feat: finish responsive application

- app/[lang]/components/login/Login.tsx
- app/[lang]/views/home/components/homeContent/HomeContent.tsx
- app/[lang]/views/home/components/profile/ModalAlertLimit.tsx
- app/[lang]/views/home/components/profile/ModalProfile.tsx
- app/[lang]/views/home/components/profile/Profile.tsx
- app/[lang]/views/home/components/profile/TextAreaForm.tsx
- app/[lang]/views/profileRecoverPassword/components/ChangePassword.tsx
- app/[lang]/views/recoverPassword/components/CreateNewPassword.tsx
- app/[lang]/views/recoverPassword/components/PasswordModifiedSuccessfully.tsx
- app/[lang]/views/recoverPassword/components/RecoveryCode.tsx
- app/[lang]/views/recoverPassword/components/RecoveryPassword.tsx
> Advance QAFixes

- app/[lang]/components/customSwitch/CustomSwitch.tsx
- app/[lang]/components/customSwitchGeneral/CustomSwitchGeneral.tsx
- app/[lang]/components/login/hooks/LoginHook.tsx
- app/[lang]/components/menu/ItemMenu.tsx
- app/[lang]/firebase/user.ts
- app/[lang]/hooks/validatorSession/ValidatorSession.tsx
- app/[lang]/reactQuery/users.tsx
- app/[lang]/types/user.ts
- app/[lang]/views/cardView/hooks/CardViewHookWithUser.tsx
- app/[lang]/views/login/hooks/LoginHookMain.tsx
- app/[lang]/views/login/page.tsx
> Diego: integration Delete/ settings switches

- app/[lang]/components/customSwitchGeneral/CustomSwitchGeneral.tsx
- app/[lang]/views/home/components/profile/FooterProfile.tsx
- app/[lang]/views/home/components/profile/ModalAlertLimit.tsx
- app/[lang]/views/home/components/profile/PhotoUser.tsx
- app/[lang]/views/home/components/profile/Profile.tsx
- app/[lang]/views/home/components/profile/hooks/ProfileHook.tsx
- app/[lang]/views/recoverPassword/components/RecoveryPassword.tsx
- yarn.lock
> bugFix: QaList

- app/[lang]/views/cardView/hooks/CardViewHookWithUser.tsx
- app/[lang]/views/home/components/profile/ItemFormUrl.tsx
> BugFix: Color_Url/Validation views

- app/[lang]/views/home/components/header/Header.tsx
- app/[lang]/views/home/components/homeContent/HomeContent.tsx
- app/[lang]/views/home/components/profile/ItemForm.tsx
- app/[lang]/views/home/components/profile/hooks/ProfileHook.tsx
- app/[lang]/views/home/hooks/HomeHook.tsx
- app/[lang]/views/templateSelector/components/hero/HeroProfessional.tsx
- dic/es.json
> fix: QAListFixes

- app/[lang]/components/oneTapLogo/OneTapLogo.tsx
- app/[lang]/views/templateSelector/components/InfinityHorizontalScrolling/InfinityHorizontalScrolling.tsx
- app/[lang]/views/templateSelector/components/SocialOne.tsx
- app/[lang]/views/templateSelector/components/bgImage/BgImage.tsx
- app/[lang]/views/templateSelector/components/container/ContainerColor.tsx
- app/[lang]/views/templateSelector/components/floatingButtons/FloatingButtons.tsx
- app/[lang]/views/templateSelector/components/floatingButtons/customButtons/CustomButton.tsx
- app/[lang]/views/templateSelector/components/floatingButtons/leftButtons/LeftButtons.tsx
- app/[lang]/views/templateSelector/components/floatingButtons/rightButtons/RightButtons.tsx
- app/[lang]/views/templateSelector/components/hero/HeroSocial.tsx
- app/[lang]/views/templateSelector/components/saveContactButton/SaveContactButtonColor.tsx
> BugFix: ResponsiveSocialOne

- app/[lang]/components/oneTapLogo/OneTapLogo.tsx
- app/[lang]/views/templateSelector/components/ProfessionalOne.tsx
- app/[lang]/views/templateSelector/components/SocialTwo.tsx
- app/[lang]/views/templateSelector/components/avatar/RectangularCustomAvatar.tsx
- app/[lang]/views/templateSelector/components/container/ContainerProfessionalOne.tsx
- app/[lang]/views/templateSelector/components/floatingButtons/customButtons/CustomButton.tsx
- app/[lang]/views/templateSelector/components/hero/HeroProfessional.tsx
- app/[lang]/views/templateSelector/components/hero/HeroSocial.tsx
> BugFix: Responsive cards

- app/[lang]/views/templateSelector/components/container/ContainerProfessionalOne.tsx
> BugFix: Responsive cardsV2

- app/[lang]/components/oneTapLogo/OneTapLogo.tsx
- app/[lang]/views/templateSelector/components/container/ContainerColor.tsx
- app/[lang]/views/templateSelector/components/floatingButtons/customButtons/CustomButton.tsx
- app/[lang]/views/templateSelector/components/hero/HeroSocial.tsx
> BugFix: Responsive cardsV3

- app/[lang]/globals/functionsTemplateProfessionalOne.ts
- app/[lang]/views/templateSelector/components/SocialTwo.tsx
- app/[lang]/views/templateSelector/components/avatar/RectangularCustomAvatar.tsx
- app/[lang]/views/templateSelector/components/container/ContainerProfessionalOne.tsx
- app/[lang]/views/templateSelector/components/floatingButtons/verticalColButtons/VerticalColButons.tsx
- app/[lang]/views/templateSelector/components/hero/HeroProfessional.tsx
- app/[lang]/views/templateSelector/components/saveContactButton/SaveContactButton.tsx
- app/[lang]/views/templateSelector/components/saveContactButton/SaveContactButtonColor.tsx
> Feat: Changes/Fixes Cards

- app/[lang]/views/templateSelector/components/container/ContainerProfessionalOne.tsx
- app/[lang]/views/templateSelector/components/hero/HeroProfessional.tsx
> BugFix: Resposive card

- app/[lang]/components/customCheckbox/CustomCheckbox.tsx
- app/[lang]/components/userRegisterForm/UserRegisterForm.tsx
- app/[lang]/components/userRegisterForm/hooks/UserRegisterForm.tsx
- app/[lang]/reactQuery/users.tsx
- app/[lang]/types/user.ts
- app/[lang]/views/home/components/profile/PhotoUser.tsx
- app/[lang]/views/home/components/profile/Profile.tsx
- app/[lang]/views/home/components/profile/ProfileProfessional.tsx
- app/[lang]/views/templateSelector/components/SocialOne.tsx
- app/[lang]/views/templateSelector/components/container/ContainerColor.tsx
> Fix: PhotosUsers

- app/[lang]/views/templateSelector/components/ProfessionalOne.tsx
> BugFix: changePhotoTemplates

- app/[lang]/components/customSwitch/CustomSwitch.tsx
- app/[lang]/components/login/hooks/LoginHook.tsx
- app/[lang]/components/userRegisterForm/hooks/UserRegisterForm.tsx
- app/[lang]/components/userTable/SwitchEdit.tsx
- app/[lang]/components/userTable/UserTable.tsx
- app/[lang]/components/userTable/hooks/UserTable.tsx
- app/[lang]/firebase/user.ts
- app/[lang]/reactQuery/users.tsx
- app/[lang]/types/user.ts
- app/[lang]/views/home/components/form/FormDataUser.tsx
- app/[lang]/views/home/components/profile/TextAreaForm.tsx
- app/[lang]/views/home/components/profile/hooks/ProfileProfessoinalHook.tsx
- app/[lang]/views/login/hooks/LoginHookMain.tsx
- app/[lang]/views/templateSelector/components/container/ContainerProfessionalOne.tsx
- app/[lang]/views/templateSelector/components/saveContactButton/SaveContactButton.tsx
- app/[lang]/views/templateSelector/components/saveContactButton/SaveContactButtonColor.tsx
- app/api/register/post/route.tsx
- app/functions/register.ts
> BugFix: duplicateData/CardsContact

- app/[lang]/components/customersDistributor/CustomersCreateForm.tsx
- app/[lang]/components/customersDistributor/CustomersDistributorForm.tsx
- app/[lang]/components/customersDistributor/hooks/CustomersCreateFormHook.tsx
- app/[lang]/components/customersDistributor/hooks/CustomersDistributorHook.tsx
- app/[lang]/firebase/Documents.ts
- app/[lang]/reactQuery/generalQueries.tsx
- app/[lang]/types/user.ts
- app/[lang]/views/backOffice/page.tsx
- app/wompi/index.js
> Wompi-integration

- app/[lang]/components/cardRegisterForm/CardRegisterForm.tsx
- app/[lang]/components/cardRegisterForm/hooks/CardRegisterFormHook.tsx
- app/[lang]/components/customersDistributor/PaymentForm.tsx
- app/[lang]/components/userTable/UserTable.tsx
- app/[lang]/components/userTable/hooks/UserTable.tsx
- app/[lang]/firebase/Documents.ts
- app/[lang]/hooks/validatorSession/ValidatorSession.tsx
- app/[lang]/reactQuery/users.tsx
- app/[lang]/views/home/components/profile/ItemForm.tsx
- app/[lang]/views/profileEdit/components/profile/PhotoUser.tsx
- app/[lang]/views/profileEdit/components/profile/Profile.tsx
- app/[lang]/views/profileEdit/components/profile/hooks/ProfileHook.tsx
- app/[lang]/views/profileEdit/hooks/HomeHook.tsx
- app/[lang]/views/profileEdit/page.tsx
> add-edit-profile-option

- app/[lang]/components/customersDistributor/hooks/CustomersCreateFormHook.tsx
- app/[lang]/firebase/user.ts
- app/functions/register.ts
…creacion de modal para editar perfil en clientes de distribuidores
> creación de modal de detalles en los modulos de reportes y clientes
